version: 2
jobs:
    deploy-production:
        working_directory: ~/app
        docker:
            - image: buildpack-deps
        steps:
            - run:
                name: Trigger Deploy
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        curl --user ${CIRCLE_API_TOKEN_FOR_DEPLOY}: \
                            --data build_parameters[CIRCLE_JOB]=build \
                            https://circleci.com/api/v1.1/project/github/mark86092/goodjob-deploy-ci/tree/check-in-bot
                    fi
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy-production:
                filters:
                    branches:
                        only: master
